# Generated by Django 5.1 on 2025-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
