# Generated by Django 5.1 on 2025-06-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_cart_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totle_price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totle_price',
            new_name='total_price',
        ),
    ]
