# Generated by Django 5.1 on 2025-06-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_rename_totle_price_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='mob',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.CharField(default='12', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
