# Generated by Django 5.2.3 on 2025-07-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
